### ISSUE TITLE
(apigatewayv2): grant permissions for sending messages to a WebSocket #14828

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/aws-cdk#2]
Issue #14828 in the base repo.

**Comment by douglasnaphas** [comment]
# TODO
- [ ] See what the integration test runner[s] do[es]. Does it clean up? When does it compare the template to the `.expected` file, and when does it instantiate resources?
- [ ] Figure out how to run just one integration test on apigatewayv2.
- [ ] Does the integration test itself clean up after itself?
- [ ] Add a minimal integration test to apigatewayv2, and run it.
- [ ] Make my integration test clean up after itself.
- [ ] Make my integration test grant permissions for sending messages to a WebSocket using the workaround, and test that this works.
- [ ] What's the difference between ManageConnections and Invoke, anyway? When do you need each?
